### ISSUE TITLE
modem_core.c missing 230400 case in switch (speed)

### ISSUE THREAD

**Issue by cbmbas** [go4retro/tcpser#10]
230400 is missing in case I guess.

While you are at it, could you also implement 460.800 so we could use it with a Silversurfer Card at full speed (at least for testing, if this will ever work...) ?

  mdm_responses[MDM_RESP_CONNECT_115200] = "CONNECT 115200";
  mdm_responses[MDM_RESP_CONNECT_230400] = "CONNECT 230400";
  return 0;
}

int get_connect_response(int speed, int level)
{
  if (level == 0) {
    return MDM_RESP_CONNECT;
  }
  switch (speed) {
  case 115200:
    return MDM_RESP_CONNECT_115200;
  case 57600:

**Comment by go4retro** [comment]
Sorry for the delay.

I looked at the code, and the case is there in the source.  Can you confirm?
