### ISSUE TITLE
missing {

### ISSUE THREAD

**Issue by mausalimi** [go4retro/tcpser#11]
last commit missis the bracket.

**Comment by go4retro** [comment]
Can you provide more clarity (what line?)  It builds fine for me.

**Comment by mausalimi** [comment]
well only a single line changed, so it is 

line 56

in ipc.c


also there's a bunch of ugly (although harmless) compiler warnings, at least in cygwin

**Comment by go4retro** [comment]
sync and compile again and see if the problems are addressed.  I did have some uncommitted fixes that I just uploaded, so perhaps I fixed the '{' and just didn't get it committed.  Still, I am compiling on cygwin here with GCC 10.2.0, and there's currently only 1 warning (in getcmd.c).

**Comment by mausalimi** [comment]
ah, that looks really different now, it does compile out of the box.

however, i get 9 warnings in getcmd.c, all of the same type "Warning array subscript has type 'char' [-Wchar-subscripts]"

but this is in an ancient cygwin, usually i use msys... so i guess it's all fine.

**Comment by go4retro** [comment]
I'd grab a more recent cygwin (mine's from a few months ago), as only 1 should be showing up.  Glad to hear it is now resolved.
