### ISSUE TITLE
Latest Source..

### ISSUE THREAD

**Issue by bucko219** [go4retro/tcpser#28]
I don't know maybe it is me, but I see the new commits, but when I download the zip file they are not included, and if I pull from svn they don't download.. All I get is the release from 2020.. Anything I might be doing wrong??

**Comment by radius75** [comment]
I can only confirm that the ZIP is up to date. Files from June 26, 2023. 
```go4retro / tcpser master  14ab39c7 (14ab39c7ebbfd4fee7e329f7c398ff0e89fcc405)```
Maybe you are pulling from wrong repo or from the wrong Master Branch
![obraz](https://github.com/go4retro/tcpser/assets/1929111/77a85981-c03e-4a22-85c9-0e53da42b9dd)
![obraz](https://github.com/go4retro/tcpser/assets/1929111/2d870acd-e196-4367-8da0-5b766c0fac1e)

**Comment by bucko219** [comment]
Everthing I download has the correct date, but not the ring modifications in the files..  I am downloading from Master If i add in the -r switch tcpser does not run. If I do a ./tcpser it doesn't even show the -r switch.. Not sure what is going on..

**Comment by radius75** [comment]
If you look at the changes in last master commit ```14ab39c7``` -r has been removed, don't use it. RI seems to be permanently on.
But it doesn't seem to be working properly yet (look at ```Issue #27```)

**Comment by bucko219** [comment]
Jeez, sorry for wasting time i should have known it was something like that!!
